name: 'HCL OneTest WEBUI'
description: 'This Action to execute WebUI test from GitHub Action.'
inputs:
  imshared:
    description: 'The path to the IMShared folder in your local installation, if it is not at default location. This is where plugins and product dependencies will be located by the execution agent, required if Config File is not specified'
    required: false

  workspace:
    description: 'The complete path to the Eclipse workspace, required if Config File is not specified'
    required: true

  project:
    description: 'The name of a project within the workspace to use, required if Config File is not specified'
    required: true

  suite:
    description: 'The name of a test within the project to use. A test can be WebUI test, Compound test, Performance schedule or Accelerated Functional Test (AFT) suite, required if Config File is not specified'
    required: true

  configFile:
    description: 'Use this option to specify the complete path to a file that contains the parameters for a test run'
    required: false

  exportReport:
    description: 'Use this option to export the unified report to any of the formats - PDF, XML or HTML. For example, to export the report to only the pdf format, you can input: type=unified;format=pdf;folder=path;filename=testreport. If you want to export the report to multiple formats, you can specify the file formats as comma-separated values.'
    required: false

  exportStats:
    description: 'Use this option to export reports in comma-separated values (CSV) format'
    required: false

  exportStatsHtml:
    description: 'Use this option if you want to export web analytic results only. The results are exported in the specified directory. You can then analyze the results on a web browser without using the test workbench.'
    required: false

  exportStatsFormat:
    description: 'Use this option to set report type csv or json'
    required: false

  multipleValues: 
    description: 'Specify the remaining inputs in the Key=Value format. Ex: Key1=Value1|Key2=Value2. Refer ReadMe'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
